### ISSUE TITLE
PositiveRate : `陽性者数 > 検査件数` だと？グラフが壊れる

### ISSUE THREAD

**Issue by suzuryo** [MeditationDuck/covid19#1637]
## 起こっている問題 / The Problem
- 今日の発表が `陽性者数 > 検査件数` だから？PositiveRateのグラフが壊れた

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/242669/117252887-888eb480-ae81-11eb-9225-b0a71dcc3af7.png)

**Comment by suzuryo** [comment]
https://github.com/MeditationDuck/covid19/issues/1314
と同じ症状なので、GoogleSheetsの方を編集して解決

**Comment by suzuryo** [comment]
- 検査した中での陽性例はその日に報告
- 検査した数は後でまとめて報告して良い

というルールがあるため、検査した数の報告が、どこかで遅れたり溜まったりしていると、`陽性数 > 検査件数` のパターンが発生する

**Comment by suzuryo** [comment]
これの関係で、rspecの `検査の陽性率` の値が合わなくて fails している

```
Failures:

  1) iPhone 6/7/8 page / 検査の陽性率(PositiveRateCard) 項目の値
     Failure/Error: expect(find('#PositiveRateCard > div > div > div.DataView-Header > div > div:nth-child(1) > div > span > strong').text).to eq d.to_s
     
       expected: "8.9"
            got: "9.1"
     
       (compared using ==)
     # ./spec/lib/PositiveRateCard.rb:33:in `has_positive_rate_card'
     # ./spec/feature/index/index_PositiveRateCard_spec.rb:18:in `block (5 levels) in <top (required)>'
```
